services:
  web:
    image: nginx:alpine
    # image: webslab/base:latest
    ports:
      - "8000:80"
    volumes:
      # - ./dist/base:/var/www/html/base
      # - ./dist:/var/www/html
      #
      - ./public:/var/www/html/base
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    image: webslab/filefind:latest
    network_mode: service:web
    volumes:
      # - ./dist:/app/resources
      #
      - ./public:/app/resources
